version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/backend-python/picture_show"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/frontend-android/picture_show"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"