# Generated by Django 6.0.6 on 2026-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='api/static/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguindo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
